import { createStitches } from '@stitches/react';
import { spacings } from './spacing.config';
import {
    gray,
    blue,
    blueDark,
    red,
    redDark,
    green,
    greenDark,
    pink,
    pinkDark,
    purple,
    purpleDark,
    violet,
    violetDark,
    cyan,
    cyanDark,
    teal,
    tealDark,
    orange,
    orangeDark,
    brown,
    brownDark,
    sky,
    skyDark,
    mint,
    mintDark,
    lime,
    limeDark,
    yellow,
    yellowDark,
    amber,
    amberDark,
    slate,
    slateDark,
    olive,
    oliveDark,
    sage,
    sageDark,
    gold,
    goldDark,
    blackA,
    whiteA,
    grayDark,
} from '@radix-ui/colors';

export const {
    styled,
    css,
    globalCss,
    keyframes,
    getCssText,
    theme,
    createTheme,
    config,
} = createStitches({
    theme: {
        colors: {
            ...gray,
            ...grayDark,
            ...blue,
            ...blueDark,
            ...red,
            ...redDark,
            ...green,
            ...greenDark,
            ...pink,
            ...pinkDark,
            ...purple,
            ...purpleDark,
            ...violet,
            ...violetDark,
            ...cyan,
            ...cyanDark,
            ...teal,
            ...tealDark,
            ...orange,
            ...orangeDark,
            ...brown,
            ...brownDark,
            ...sky,
            ...skyDark,
            ...mint,
            ...mintDark,
            ...lime,
            ...limeDark,
            ...yellow,
            ...yellowDark,
            ...amber,
            ...amberDark,
            ...slate,
            ...slateDark,
            ...olive,
            ...oliveDark,
            ...sage,
            ...sageDark,
            ...gold,
            ...goldDark,
            ...blackA,
            ...whiteA,
        },
    },
    space: {
        1: '5px',
        2: '10px',
        3: '15px',
    },
    size: {
        1: '5px',
        2: '10px',
        3: '15px',
    },
    media: {
        sm: "@media (min-width: 576px)",
        md: "@media (min-width: 768px)",
        lg: "@media (min-width: 992px)",
        xl: "@media (min-width: 1200px)",
    },
    utils: {},
});

const globalStyles = globalCss({
    '*': {
        margin: 0,
        boxSizing: "border-box",
        padding: 0,
        fontFamily: `-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`
    },
});

globalStyles()